### ISSUE TITLE
Wrong Python signature of _spherepack functions with Meson build

### ISSUE THREAD

**Issue by DominikStiller** [jswhit/pyspharm#15]
I am having issues with pyspharm installed through pip after it switched to the Meson build system (#13 and #14). Note that the setup.py installation does not work anymore with Meson, so the installation necessarily needs to be through pip.

First, I had to add the Python sources to the installation since only the _spherepack.*.so file was installed. I can open a PR for that: https://github.com/DominikStiller/pyspharm/commit/ddc2d8d44e0069b91c8b5264dec01cadc32dcefb

It then appears that the Python function signature generated by F2PY is different when building with Meson. For example, running
```python
import spharm
spharm.Spharmt(20, 20)
```
fails with the message
```
---------------------------------------------------------------------------
TypeError                                 Traceback (most recent call last)
Cell In[6], line 4
      1 import spharm
----> 2 spharm.Spharmt(20, 20)

File ~/.local/software/miniconda3/envs/lmrecon/lib/python3.11/site-packages/spharm/spharm.py:246, in Spharmt.__init__(self, nlon, nlat, rsphere, gridtype, legfunc)
    244 lshaes = (n1*n2*(nlat + nlat - n1 + 1))/2 + nlon + 15
    245 lwork = 5*nlat*n2 + 3*((n1 - 2)*(nlat + nlat - n1 -1))/2
--> 246 wshaes, ierror = _spherepack.shaesi(nlat, nlon, lshaes, lwork, nlat+1)
    247 if ierror != 0:
    248     msg = 'In return from call to shaesi in Spharmt.__init__ ierror =  %d' % ierror

TypeError: _spherepack.shaesi() missing required argument 'lwork' (pos 6)
```
while it worked before #13 and #14 (tagging @DWesl, who worked on them). It seems that Fortran arguments with `intent(out)` or ` intent(cache,hide)` are treated as regular arguments in the Python wrapper. Maybe, this is an issue with different Fortran language or compiler versions used by Meson.

My NumPy version is 2.0.1

**Comment by DWesl** [comment]
> I am having issues with pyspharm installed through pip after it switched to the Meson build system (#13 and #14). Note that the setup.py installation does not work anymore with Meson, so the installation necessarily needs to be through pip.
> 
> First, I had to add the Python sources to the installation since only the _spherepack.*.so file was installed. I can open a PR for that: [DominikStiller@ddc2d8d](https://github.com/DominikStiller/pyspharm/commit/ddc2d8d44e0069b91c8b5264dec01cadc32dcefb)

Good catch, I'm still getting used to Meson.
> 
> It then appears that the Python function signature generated by F2PY is different when building with Meson. For example, running
> 
> ```python
> import spharm
> spharm.Spharmt(20, 20)
> ```
> 
> fails with the message
> 
> ```
> ---------------------------------------------------------------------------
> TypeError                                 Traceback (most recent call last)
> Cell In[6], line 4
>       1 import spharm
> ----> 2 spharm.Spharmt(20, 20)
> 
> File ~/.local/software/miniconda3/envs/lmrecon/lib/python3.11/site-packages/spharm/spharm.py:246, in Spharmt.__init__(self, nlon, nlat, rsphere, gridtype, legfunc)
>     244 lshaes = (n1*n2*(nlat + nlat - n1 + 1))/2 + nlon + 15
>     245 lwork = 5*nlat*n2 + 3*((n1 - 2)*(nlat + nlat - n1 -1))/2
> --> 246 wshaes, ierror = _spherepack.shaesi(nlat, nlon, lshaes, lwork, nlat+1)
>     247 if ierror != 0:
>     248     msg = 'In return from call to shaesi in Spharmt.__init__ ierror =  %d' % ierror
> 
> TypeError: _spherepack.shaesi() missing required argument 'lwork' (pos 6)
> ```
> 
> while it worked before #13 and #14 (tagging @DWesl, who worked on them). It seems that Fortran arguments with `intent(out)` or ` intent(cache,hide)` are treated as regular arguments in the Python wrapper. Maybe, this is an issue with different Fortran language or compiler versions used by Meson.
> 
> My NumPy version is 2.0.1

Does it work with `numpy<2.0.0` in the `pyproject.toml`?  If not, I may have to go spelunking in `numpy.distutils` for their `f2py` options.

**Comment by DominikStiller** [comment]
It also does not work with NumPy 1.26. Also, it fails with both Python 3.11 and 3.12.

**Comment by DWesl** [comment]
I can reproduce the issue: moving the `f2py` options before the list of files might have let me run that example, but `examples/regrid_test.py` still fails.

`f2py -c --backend meson --build-dir temp src/*.pyf src/*.f` produced a working `temp/_spherepackmodule.c`, but I'm not too clear on the differences between `f2py -c` and separate steps of having meson run `f2py` and then compile a Python extension.

**Comment by DWesl** [comment]
Does removing the fortran files from the `spherepack_source` list of `input`s and removing `'-m', '_spherepack'` from the `command` produce a working `_spherepack` extension?  

I suspect that just removing `'-m', '_spherepack'` from the command line would work, but the `pyf` file already has all the information it would need from the fortran files, so I'd prefer to have that list of files in only one place.

**Comment by DominikStiller** [comment]
Using your https://github.com/DWesl/pyspharm/tree/patch-2 indeed seems to fix the problem! Both `examples/regrid_test.py` and `examples/galewskyetal_testcase.py` work for me (at least after casting `nlats` in the latter to `int` and updating some deprecated references, nothing related to pyspharm).

Are there any downsides to your patch? Otherwise I think you can open a PR.

**Comment by DWesl** [comment]
Added as #16, with your patch.
