### ISSUE TITLE
Successfully installed using 'git clone' but cannot import

### ISSUE THREAD

**Issue by auroralin0408** [jswhit/pyspharm#17]
I installed pyspharm using git clone in my envs, and it succeed. I can see the module in 'conda list', but when I import it, it raised ModuleNotFoundError.
<img width="672" alt="image" src="https://github.com/user-attachments/assets/908d0e48-c10e-4bc6-ac96-a1c08ce9e5d8">

**Comment by DWesl** [comment]
Have you tried `import spharm`, as done in [t](https://github.com/jswhit/pyspharm/blob/9cd7a46dd37a9fa4e9ffd4ed49952e2d4e38252c/examples/regrid_test.py#L3)[h](https://github.com/jswhit/pyspharm/blob/9cd7a46dd37a9fa4e9ffd4ed49952e2d4e38252c/examples/galewskyetal_testcase.py#L3)[e](https://github.com/jswhit/pyspharm/blob/9cd7a46dd37a9fa4e9ffd4ed49952e2d4e38252c/examples/2levelturb.py#L2) [ex](https://github.com/jswhit/pyspharm/blob/9cd7a46dd37a9fa4e9ffd4ed49952e2d4e38252c/examples/geodesic.py#L2)[am](https://github.com/jswhit/pyspharm/blob/9cd7a46dd37a9fa4e9ffd4ed49952e2d4e38252c/examples/spharmonic.py#L2)[pl](https://github.com/jswhit/pyspharm/blob/9cd7a46dd37a9fa4e9ffd4ed49952e2d4e38252c/examples/twolayer.py#L3)[es](https://github.com/jswhit/pyspharm/blob/9cd7a46dd37a9fa4e9ffd4ed49952e2d4e38252c/examples/twolevel.py#L3)?  The [setuptools](https://github.com/jswhit/pyspharm/blob/9cd7a46dd37a9fa4e9ffd4ed49952e2d4e38252c/setup.py#L59-L60) and [mesonpy](https://github.com/jswhit/pyspharm/blob/9cd7a46dd37a9fa4e9ffd4ed49952e2d4e38252c/meson.build#L16-L21) configurations suggest that is where the python files get installed.

**Comment by auroralin0408** [comment]
I tried that, but it also raised error.
<img width="1139" alt="image" src="https://github.com/user-attachments/assets/ac7a74c8-f3ae-4d33-989b-59ab34d529b7">
```
---------------------------------------------------------------------------
FileNotFoundError                         Traceback (most recent call last)
Cell In[65], line 1
----> 1 from spharm import Spharmt, getspecindx

File <frozen importlib._bootstrap>:1176, in _find_and_load(name, import_)

File <frozen importlib._bootstrap>:1138, in _find_and_load_unlocked(name, import_)

File <frozen importlib._bootstrap>:1078, in _find_spec(name, path, target)

File ~/miniforge3/envs/cmt_1.0/lib/python3.11/site-packages/_pyspharm_editable_loader.py:310, in MesonpyMetaFinder.find_spec(self, fullname, path, target)
    308 if self._build_path in os.environ.get(MARKER, '').split(os.pathsep):
    309     return None
--> 310 tree = self._rebuild()
    311 return find_spec(fullname, tree)

File ~/miniforge3/envs/cmt_1.0/lib/python3.11/site-packages/_pyspharm_editable_loader.py:343, in MesonpyMetaFinder._rebuild(self)
    341         subprocess.run(self._build_cmd, cwd=self._build_path, env=env)
    342 else:
--> 343     subprocess.run(self._build_cmd, cwd=self._build_path, env=env, stdout=subprocess.DEVNULL)
    345 install_plan_path = os.path.join(self._build_path, 'meson-info', 'intro-install_plan.json')
    346 with open(install_plan_path, 'r', encoding='utf8') as f:

File ~/miniforge3/envs/cmt_1.0/lib/python3.11/subprocess.py:548, in run(input, capture_output, timeout, check, *popenargs, **kwargs)
    545     kwargs['stdout'] = PIPE
    546     kwargs['stderr'] = PIPE
--> 548 with Popen(*popenargs, **kwargs) as process:
    549     try:
    550         stdout, stderr = process.communicate(input, timeout=timeout)

File ~/miniforge3/envs/cmt_1.0/lib/python3.11/subprocess.py:1026, in Popen.__init__(self, args, bufsize, executable, stdin, stdout, stderr, preexec_fn, close_fds, shell, cwd, env, universal_newlines, startupinfo, creationflags, restore_signals, start_new_session, pass_fds, user, group, extra_groups, encoding, errors, text, umask, pipesize, process_group)
   1022         if self.text_mode:
   1023             self.stderr = io.TextIOWrapper(self.stderr,
   1024                     encoding=encoding, errors=errors)
-> 1026     self._execute_child(args, executable, preexec_fn, close_fds,
   1027                         pass_fds, cwd, env,
   1028                         startupinfo, creationflags, shell,
   1029                         p2cread, p2cwrite,
   1030                         c2pread, c2pwrite,
   1031                         errread, errwrite,
   1032                         restore_signals,
   1033                         gid, gids, uid, umask,
   1034                         start_new_session, process_group)
   1035 except:
   1036     # Cleanup if the child failed starting.
   1037     for f in filter(None, (self.stdin, self.stdout, self.stderr)):

File ~/miniforge3/envs/cmt_1.0/lib/python3.11/subprocess.py:1950, in Popen._execute_child(self, args, executable, preexec_fn, close_fds, pass_fds, cwd, env, startupinfo, creationflags, shell, p2cread, p2cwrite, c2pread, c2pwrite, errread, errwrite, restore_signals, gid, gids, uid, umask, start_new_session, process_group)
   1948     if errno_num != 0:
   1949         err_msg = os.strerror(errno_num)
-> 1950     raise child_exception_type(errno_num, err_msg, err_filename)
   1951 raise child_exception_type(err_msg)

FileNotFoundError: [Errno 2] No such file or directory: '/private/var/folders/vd/bkwh6_w97nd4zm9zfky7v8s80000gn/T/pip-build-env-41yplss2/normal/bin/ninja'

**Comment by DWesl** [comment]
So that's recognizing `spharm` as a module to import, that's progress.  It looks like an editable install having problems finding ninja to recompile the fortran files.  Options to fix:
- Install ninja (and meson-python, which you already have) alongside pyspharm (run `pip install ninja`)
- Switch to a non-editable install (`pip install --force-reinstall --no-deps /path/to/pyspharm` or `pip uninstall pyspharm; pip install /path/to/pyspharm`)

**Comment by auroralin0408** [comment]
Thanks a lot! I fixed it with the second option.
